#### ML Concept Revision

In [1]:
import pandas as pd
data = {
     'name':['alex','kush','ankit','kaveri'],
     'age':[21,None,22,None],
     'salary':[80000,70000,50000,45000]
}

df = pd.DataFrame(data)
print("Original DataFrame")
print(df)

Original DataFrame
     name   age  salary
0    alex  21.0   80000
1    kush   NaN   70000
2   ankit  22.0   50000
3  kaveri   NaN   45000

In [2]:
print(df.isnull().sum())

name      0
age       2
salary    0
dtype: int64

In [3]:
df_drop = df.dropna()

In [4]:
print(df_drop)

    name   age  salary
0   alex  21.0   80000
2  ankit  22.0   50000

- Data Preproccesing & Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

df = pd.read_csv("data.csv")
df

      Name  Gender       City Passed
0     Aman    Male      Delhi    Yes
1    Priya  Female     Mumbai    Yes
2    Rahul    Male  Bangalore     No
3   Anjali  Female     Mumbai    Yes
4     Ravi    Male      Delhi    Yes
5    Meera  Female    Chennai     No
6    Arjun    Male  Bangalore    Yes
7     Neha  Female      Delhi    Yes
8    Imran    Male    Chennai     No
9    Sneha  Female     Mumbai    Yes
10     Raj    Male    Chennai    Yes
11   Divya  Female      Delhi     No
12   Kabir    Male     Mumbai    Yes
13  Simran  Female  Bangalore    Yes
14   Karan    Male      Delhi     No
15   Pooja  Female     Mumbai    Yes
16  Rakesh    Male    Chennai    Yes
17    Isha  Female      Delhi     No
18   Rohit    Male      Delhi    Yes
19   Deepa  Female  Bangalore    Yes

In [7]:
df_label = df.copy()

le = LabelEncoder()
df_label['Gender_Encoded'] = le.fit_transform(df_label['Gender'])
df_label['Passed_Encoded'] = le.fit_transform(df_label['Passed'])

print("Label Encoded Data")
print(df_label[['Name','Gender','Gender_Encoded','Passed_Encoded']])

Label Encoded Data
      Name  Gender  Gender_Encoded  Passed_Encoded
0     Aman    Male               1               1
1    Priya  Female               0               1
2    Rahul    Male               1               0
3   Anjali  Female               0               1
4     Ravi    Male               1               1
5    Meera  Female               0               0
6    Arjun    Male               1               1
7     Neha  Female               0               1
8    Imran    Male               1               0
9    Sneha  Female               0               1
10     Raj    Male               1               1
11   Divya  Female               0               0
12   Kabir    Male               1               1
13  Simran  Female               0               1
14   Karan    Male               1               0
15   Pooja  Female               0               1
16  Rakesh    Male               1               1
17    Isha  Female               0               0
18   Rohit    Male               1               1
19   Deepa  Female               0               1

In [8]:
df_encoded = pd.get_dummies(df_label,columns=["City"])
print(df_encoded)

      Name  Gender Passed  Gender_Encoded  Passed_Encoded  City_Bangalore  \
0     Aman    Male    Yes               1               1           False
1    Priya  Female    Yes               0               1           False
2    Rahul    Male     No               1               0            True
3   Anjali  Female    Yes               0               1           False
4     Ravi    Male    Yes               1               1           False
5    Meera  Female     No               0               0           False
6    Arjun    Male    Yes               1               1            True
7     Neha  Female    Yes               0               1           False
8    Imran    Male     No               1               0           False
9    Sneha  Female    Yes               0               1           False
10     Raj    Male    Yes               1               1           False
11   Divya  Female     No               0               0           False
12   Kabir    Male    Yes               1               1           False
13  Simran  Female    Yes               0               1            True
14   Karan    Male     No               1               0           False
15   Pooja  Female    Yes               0               1           False
16  Rakesh    Male    Yes               1               1           False
17    Isha  Female     No               0               0           False
18   Rohit    Male    Yes               1               1           False
19   Deepa  Female    Yes               0               1            True

    City_Chennai  City_Delhi  City_Mumbai
0          False        True        False
1          False       False         True
2          False       False        False
3          False       False         True
4          False        True        False
5           True       False        False
6          False       False        False
7          False        True        False
8           True       False        False
9          False       False         True
10          True       False        False
11         False        True        False
12         False       False         True
13         False       False        False
14         False        True        False
15         False       False         True
16          True       False        False
17         False        True        False
18         False        True        False
19         False       False        False

- Standard Scaler & Minmax Scaler

In [ ]:
# scaler = StandardScaler()
# X_scaled = scaler.fit_transform()

# scaler = MinMaxScaler()
# x_s1caled = scaler.fit_transform()

In [20]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split

data = {
     'Study_Hrs':[1,2,3,4,5],
     'Test_Scr':[40,50,60,90,100]
}
df = pd.DataFrame(data)

In [21]:
df

   Study_Hrs  Test_Scr
0          1        40
1          2        50
2          3        60
3          4        90
4          5       100

In [22]:
## Standard Scaler
standard_scaler = StandardScaler()
standard_scaled = standard_scaler.fit_transform(df)
print(pd.DataFrame(standard_scaled,columns=['Study_Hrs','Test_Scr']))

   Study_Hrs  Test_Scr
0  -1.414214 -1.209416
1  -0.707107 -0.777482
2   0.000000 -0.345547
3   0.707107  0.950255
4   1.414214  1.382189

In [23]:
## Minmax Scaler
standard_scaler = MinMaxScaler()
standard_scaled = standard_scaler.fit_transform(df)
print(pd.DataFrame(standard_scaled,columns=['Study_Hrs','Test_Scr']))

   Study_Hrs  Test_Scr
0       0.00  0.000000
1       0.25  0.166667
2       0.50  0.333333
3       0.75  0.833333
4       1.00  1.000000

In [24]:
X = df[['Study_Hrs']]
Y = df[['Test_Scr']]

X_Train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [25]:
print(X_Train)

   Study_Hrs
4          5
2          3
0          1
3          4

In [26]:
print(X_test)

   Study_Hrs
1          2

- Supervised Learning Algos