### Data Collection Techniques Day_15
***
- **Web Scarpping**
- Scraping websites
   - **toscrape.com**
   - **scrapethesissite.com**

In [2]:
!pip install requests

Requirement already satisfied: requests in d:\aiml prime\venv\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\aiml prime\venv\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\aiml prime\venv\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\aiml prime\venv\lib\site-packages (from requests) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in d:\aiml prime\venv\lib\site-packages (from requests) (2025.11.12)

- Using requests

In [4]:
import requests
URL = "https://stephen-king-api.onrender.com/api/books"
res = requests.get(URL)

print(res.status_code)
print(res.headers)

200
{'Date': 'Sun, 14 Dec 2025 01:40:33 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'access-control-allow-origin': '*', 'etag': 'W/"696f-W8etsExFqAJgjLqJa20LIWLl3iI"', 'rndr-id': '8a470805-abd7-4979', 'vary': 'Accept-Encoding', 'x-powered-by': 'Express', 'x-render-origin-server': 'Render', 'cf-cache-status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '9ad9fe633cd5ff99-BOM', 'alt-svc': 'h3=":443"; ma=86400'}

In [6]:
json_data = res.json()
json_data

{'data': [{'id': 1,
   'Year': 1974,
   'Title': 'Carrie',
   'handle': 'carrie',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-08695-0',
   'Pages': 199,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:47.848Z',
   'villains': [{'name': 'Tina Blake',
     'url': 'https://stephen-king-api.onrender.com/api/villain/4'},
    {'name': 'Cindi',
     'url': 'https://stephen-king-api.onrender.com/api/villain/14'},
    {'name': 'Myra Crewes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/16'},
    {'name': 'Billy deLois',
     'url': 'https://stephen-king-api.onrender.com/api/villain/25'},
    {'name': 'Kenny Garson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/38'},
    {'name': 'Mary Lila Grace',
     'url': 'https://stephen-king-api.onrender.com/api/villain/44'},
    {'name': 'Christine Hargensen',
     'url': 'https://stephen-king-api.onrender.com/api/villain/49'},
    {'name': 'Vic Mooney',
     'url': 'https://stephen-king-api.onrender.com/api/villain/75'},
    {'name': 'The Mortimer Snerds',
     'url': 'https://stephen-king-api.onrender.com/api/villain/77'},
    {'name': 'Billy Nolan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/80'},
    {'name': 'Elenor Richmond',
     'url': 'https://stephen-king-api.onrender.com/api/villain/90'},
    {'name': 'Rachel Spies',
     'url': 'https://stephen-king-api.onrender.com/api/villain/94'},
    {'name': 'Jackie Talbot',
     'url': 'https://stephen-king-api.onrender.com/api/villain/99'},
    {'name': 'Donna and Mary Lila Grace Thibodeau',
     'url': 'https://stephen-king-api.onrender.com/api/villain/102'},
    {'name': 'Jessica Upshaw',
     'url': 'https://stephen-king-api.onrender.com/api/villain/108'},
    {'name': 'Norma Watson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/109'},
    {'name': 'Margaret White',
     'url': 'https://stephen-king-api.onrender.com/api/villain/113'}]},
  {'id': 2,
   'Year': 1975,
   'Title': "Salem's Lot",
   'handle': 'salem-s-lot',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-00751-1',
   'Pages': 439,
   'Notes': ['Nominee, World Fantasy Award, 1976[2]'],
   'created_at': '2023-11-13T23:48:48.098Z',
   'villains': [{'name': 'Kurt Barlow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/2'},
    {'name': 'Richard Straker',
     'url': 'https://stephen-king-api.onrender.com/api/villain/98'}]},
  {'id': 3,
   'Year': 1977,
   'Title': 'The Shining',
   'handle': 'the-shining',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12167-5',
   'Pages': 447,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1978[2]'],
   'created_at': '2023-11-13T23:48:48.219Z',
   'villains': [{'name': 'Horace M. Derwent',
     'url': 'https://stephen-king-api.onrender.com/api/villain/26'},
    {'name': 'Delbert Grady',
     'url': 'https://stephen-king-api.onrender.com/api/villain/45'},
    {'name': 'Jack Torrance',
     'url': 'https://stephen-king-api.onrender.com/api/villain/106'}]},
  {'id': 4,
   'Year': 1977,
   'Title': 'Rage',
   'handle': 'rage',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-07645-8',
   'Pages': 211,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.339Z',
   'villains': []},
  {'id': 5,
   'Year': 1978,
   'Title': 'The Stand',
   'handle': 'the-stand',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-12168-2',
   'Pages': 823,
   'Notes': ['Nominee, World Fantasy Award, 1979',
    'Runner-up (15th place), Locus Award, 1979[2]'],
   'created_at': '2023-11-13T23:48:48.477Z',
   'villains': [{'name': 'Donald Merwin Elbert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/34'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Lloyd Henreid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/51'},
    {'name': 'The Kid',
     'url': 'https://stephen-king-api.onrender.com/api/villain/62'},
    {'name': 'Harold Lauder',
     'url': 'https://stephen-king-api.onrender.com/api/villain/64'},
    {'name': 'Rat Man',
     'url': 'https://stephen-king-api.onrender.com/api/villain/87'}]},
  {'id': 6,
   'Year': 1979,
   'Title': 'The Long Walk',
   'handle': 'the-long-walk',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-08754-6',
   'Pages': 384,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:48.608Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'The Major',
     'url': 'https://stephen-king-api.onrender.com/api/villain/70'}]},
  {'id': 7,
   'Year': 1979,
   'Title': 'The Dead Zone',
   'handle': 'the-dead-zone',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-26077-5',
   'Pages': 428,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Fantasy Novel, 1980[2]'],
   'created_at': '2023-11-13T23:48:48.753Z',
   'villains': [{'name': 'Frank Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/29'},
    {'name': 'Henrietta Dodd',
     'url': 'https://stephen-king-api.onrender.com/api/villain/30'},
    {'name': 'Malcolm Janus',
     'url': 'https://stephen-king-api.onrender.com/api/villain/71'},
    {'name': 'Sonny Elliman',
     'url': 'https://stephen-king-api.onrender.com/api/villain/93'},
    {'name': 'Greg Stillson',
     'url': 'https://stephen-king-api.onrender.com/api/villain/97'},
    {'name': "The Devil's Dozen",
     'url': 'https://stephen-king-api.onrender.com/api/villain/100'}]},
  {'id': 8,
   'Year': 1980,
   'Title': 'Firestarter',
   'handle': 'firestarter',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-31541-3',
   'Pages': 426,
   'Notes': ['Nominee, British Fantasy Award’s August Derleth Award, 1981',
    'Runner-up (8th place), Locus Award for Best Science Fiction Novel, 1981[2]'],
   'created_at': '2023-11-13T23:48:48.876Z',
   'villains': [{'name': 'James Hollister',
     'url': 'https://stephen-king-api.onrender.com/api/villain/54'},
    {'name': 'Charlie McGee',
     'url': 'https://stephen-king-api.onrender.com/api/villain/73'},
    {'name': 'John Rainbird',
     'url': 'https://stephen-king-api.onrender.com/api/villain/86'}]},
  {'id': 9,
   'Year': 1981,
   'Title': 'Roadwork',
   'handle': 'roadwork',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-09668-5',
   'Pages': 274,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.005Z',
   'villains': []},
  {'id': 10,
   'Year': 1981,
   'Title': 'Cujo',
   'handle': 'cujo',
   'Publisher': 'Viking Press',
   'ISBN': '978-0-670-45193-7',
   'Pages': 319,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1982',
    'Runner-up (21st place), Locus Award for Best Fantasy Novel, 1982[2]'],
   'created_at': '2023-11-13T23:48:49.131Z',
   'villains': [{'name': 'Cujo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/19'}]},
  {'id': 11,
   'Year': 1982,
   'Title': 'The Running Man',
   'handle': 'the-running-man',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-11508-9',
   'Pages': 219,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:49.252Z',
   'villains': [{'name': 'The Gladiators',
     'url': 'https://stephen-king-api.onrender.com/api/villain/42'},
    {'name': 'Damon Killian',
     'url': 'https://stephen-king-api.onrender.com/api/villain/63'}]},
  {'id': 12,
   'Year': 1982,
   'Title': 'The Dark Tower: The Gunslinger',
   'handle': 'the-dark-tower-the-gunslinger',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-50-9',
   'Pages': 224,
   'Notes': [''],
   'created_at': '2023-11-13T23:48:49.374Z',
   'villains': [{'name': 'Marten Broadcloak',
     'url': 'https://stephen-king-api.onrender.com/api/villain/10'},
    {'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'},
    {'name': 'Sylvia Pittston',
     'url': 'https://stephen-king-api.onrender.com/api/villain/84'}]},
  {'id': 13,
   'Year': 1983,
   'Title': 'Christine',
   'handle': 'christine',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-22026-7',
   'Pages': 526,
   'Notes': ['Runner-up (6th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.505Z',
   'villains': [{'name': 'Christine (car)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/11'},
    {'name': 'Arnie Cunningham',
     'url': 'https://stephen-king-api.onrender.com/api/villain/20'}]},
  {'id': 14,
   'Year': 1983,
   'Title': 'Pet Sematary',
   'handle': 'pet-sematary',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-18244-7',
   'Pages': 374,
   'Notes': ['Nominee, World Fantasy Award, 1984',
    'Runner-up (7th place), Locus Award for Best Fantasy Novel, 1984[2]'],
   'created_at': '2023-11-13T23:48:49.637Z',
   'villains': [{'name': 'Winston Church',
     'url': 'https://stephen-king-api.onrender.com/api/villain/13'},
    {'name': 'Gage Creed',
     'url': 'https://stephen-king-api.onrender.com/api/villain/15'},
    {'name': 'Victor Pascow',
     'url': 'https://stephen-king-api.onrender.com/api/villain/83'},
    {'name': 'Wendigo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/110'}]},
  {'id': 15,
   'Year': 1983,
   'Title': 'Cycle of the Werewolf',
   'handle': 'cycle-of-the-werewolf',
   'Publisher': 'Land of Enchantment',
   'ISBN': '978-0-960-38282-8',
   'Pages': 127,
   'Notes': ['Illustrated by Bernie Wrightson'],
   'created_at': '2023-11-13T23:48:49.757Z',
   'villains': [{'name': 'Lester Lowe',
     'url': 'https://stephen-king-api.onrender.com/api/villain/68'}]},
  {'id': 16,
   'Year': 1984,
   'Title': 'The Talisman',
   'handle': 'the-talisman',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-69199-9',
   'Pages': 646,
   'Notes': ['Written with Peter Straub',
    'Nominee, World Fantasy Award, 1985',
    'Runner-up (4th place), Locus Award for Best Fantasy Novel, 1985[2]'],
   'created_at': '2023-11-13T23:48:49.872Z',
   'villains': []},
  {'id': 17,
   'Year': 1984,
   'Title': 'The Eyes of the Dragon',
   'handle': 'the-eyes-of-the-dragon',
   'Publisher': 'Philtrum Press (1984)Viking (1987)',
   'ISBN': '978-0-670-81458-9',
   'Pages': 326,
   'Notes': ['First published as a limited edition in 1984, then for the mass market in 1987'],
   'created_at': '2023-11-13T23:48:49.988Z',
   'villains': [{'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 18,
   'Year': 1984,
   'Title': 'Thinner',
   'handle': 'thinner',
   'Publisher': 'NAL',
   'ISBN': '978-0-453-00468-8',
   'Pages': 309,
   'Notes': ['Published under pseudonym Richard Bachman'],
   'created_at': '2023-11-13T23:48:50.102Z',
   'villains': []},
  {'id': 19,
   'Year': 1986,
   'Title': 'It',
   'handle': 'it',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81302-5',
   'Pages': 1138,
   'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1987',
    'Nominee, World Fantasy Award, 1987',
    'Runner-up (3rd place), Locus Award for Best Fantasy Novel, 1987[2]'],
   'created_at': '2023-11-13T23:48:50.223Z',
   'villains': [{'name': 'Henry Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/7'},
    {'name': 'Butch Bowers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/8'},
    {'name': 'Greta Bowie',
     'url': 'https://stephen-king-api.onrender.com/api/villain/9'},
    {'name': 'Victor Criss',
     'url': 'https://stephen-king-api.onrender.com/api/villain/18'},
    {'name': 'Marcia Fadden',
     'url': 'https://stephen-king-api.onrender.com/api/villain/35'},
    {'name': 'John Garton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/39'},
    {'name': 'Peter Gordon',
     'url': 'https://stephen-king-api.onrender.com/api/villain/43'},
    {'name': 'Patrick Hockstetter',
     'url': 'https://stephen-king-api.onrender.com/api/villain/53'},
    {'name': 'Belch Huggins',
     'url': 'https://stephen-king-api.onrender.com/api/villain/55'},
    {'name': 'It (Creature)',
     'url': 'https://stephen-king-api.onrender.com/api/villain/57'},
    {'name': 'Richard P. Macklin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/69'},
    {'name': 'Alvin Marsh',
     'url': 'https://stephen-king-api.onrender.com/api/villain/72'},
    {'name': 'Sally Mueller',
     'url': 'https://stephen-king-api.onrender.com/api/villain/79'},
    {'name': 'Tom Rogan',
     'url': 'https://stephen-king-api.onrender.com/api/villain/91'},
    {'name': 'Christopher Unwin',
     'url': 'https://stephen-king-api.onrender.com/api/villain/107'}]},
  {'id': 20,
   'Year': 1987,
   'Title': 'The Dark Tower II: The Drawing of the Three',
   'handle': 'the-dark-tower-ii-the-drawing-of-the-three',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-90-5',
   'Pages': 400,
   'Notes': ['Runner-up (16th place), Locus Award for Best Fantasy Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.339Z',
   'villains': [{'name': 'Jack Mort',
     'url': 'https://stephen-king-api.onrender.com/api/villain/76'}]},
  {'id': 21,
   'Year': 1987,
   'Title': 'Misery',
   'handle': 'misery',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-81364-3',
   'Pages': 310,
   'Notes': ['Winner, Bram Stoker Award, 1988',
    'Nominee, World Fantasy Award, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.459Z',
   'villains': [{'name': 'Annie Wilkes',
     'url': 'https://stephen-king-api.onrender.com/api/villain/114'}]},
  {'id': 22,
   'Year': 1987,
   'Title': 'The Tommyknockers',
   'handle': 'the-tommyknockers',
   'Publisher': 'Putnam',
   'ISBN': '978-0-399-13314-5',
   'Pages': 558,
   'Notes': ['Runner-up (16th place), Locus Award for Best Science Fiction Novel, 1988[2]'],
   'created_at': '2023-11-13T23:48:50.579Z',
   'villains': [{'name': 'Tommyknockers',
     'url': 'https://stephen-king-api.onrender.com/api/villain/104'}]},
  {'id': 23,
   'Year': 1989,
   'Title': 'The Dark Half',
   'handle': 'the-dark-half',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-82982-8',
   'Pages': 431,
   'Notes': ['Runner-up (2nd place), Locus Award for Best Horror Novel, 1990[2]'],
   'created_at': '2023-11-13T23:48:50.696Z',
   'villains': [{'name': 'George Stark',
     'url': 'https://stephen-king-api.onrender.com/api/villain/96'}]},
  {'id': 24,
   'Year': 1990,
   'Title': 'The Stand Uncut',
   'handle': 'the-stand-uncut',
   'Publisher': 'Doubleday',
   'ISBN': '978-0-385-19957-5',
   'Pages': 1152,
   'Notes': ['The Complete & Uncut Edition',
    "Runner-up (2nd place), Locus Award's Best Horror/Dark Fantasy Novel, 1991[2]"],
   'created_at': '2023-11-13T23:48:50.809Z',
   'villains': []},
  {'id': 25,
   'Year': 1991,
   'Title': 'The Dark Tower III: The Waste Lands',
   'handle': 'the-dark-tower-iii-the-waste-lands',
   'Publisher': 'Grant',
   'ISBN': '978-0-937986-17-2',
   'Pages': 512,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:50.926Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Randall Flagg',
     'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]},
  {'id': 26,
   'Year': 1991,
   'Title': 'Needful Things',
   'handle': 'needful-things',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-83953-7',
   'Pages': 690,
   'Notes': ['Nominee, Bram Stoker Award, 1992',
    'Runner-up (13th place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'],
   'created_at': '2023-11-13T23:48:51.044Z',
   'villains': [{'name': 'Leland Gaunt',
     'url': 'https://stephen-king-api.onrender.com/api/villain/40'}]},
  {'id': 27,
   'Year': 1992,
   'Title': "Gerald's Game",
   'handle': 'gerald-s-game',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84650-4',
   'Pages': 352,
   'Notes': [],
   'created_at': '2023-11-13T23:48:51.165Z',
   'villains': [{'name': 'Gerald Burlingame',
     'url': 'https://stephen-king-api.onrender.com/api/villain/41'},
    {'name': 'Raymond Andrew Joubert',
     'url': 'https://stephen-king-api.onrender.com/api/villain/61'},
    {'name': 'Tom Mahout',
     'url': 'https://stephen-king-api.onrender.com/api/villain/103'}]},
  {'id': 28,
   'Year': 1992,
   'Title': 'Dolores Claiborne',
   'handle': 'dolores-claiborne',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-84452-4',
   'Pages': 305,
   'Notes': ['Runner-up (14th place), Locus Award for Best Horror/Dark Fantasy Novel, 1993[2]'],
   'created_at': '2023-11-13T23:48:51.295Z',
   'villains': [{'name': 'Joe St. George',
     'url': 'https://stephen-king-api.onrender.com/api/villain/95'}]},
  {'id': 29,
   'Year': 1994,
   'Title': 'Insomnia',
   'handle': 'insomnia',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85503-2',
   'Pages': 787,
   'Notes': ['Nominee, Bram Stoker Award, 1995',
    'Runner-up (3rd place), Locus Award for Best Fantasy/Horror Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.415Z',
   'villains': [{'name': 'Crimson King',
     'url': 'https://stephen-king-api.onrender.com/api/villain/17'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 30,
   'Year': 1995,
   'Title': 'Rose Madder',
   'handle': 'rose-madder',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-85869-9',
   'Pages': 420,
   'Notes': ['Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1995[2]'],
   'created_at': '2023-11-13T23:48:51.533Z',
   'villains': [{'name': 'Norman Daniels',
     'url': 'https://stephen-king-api.onrender.com/api/villain/22'},
    {'name': 'Susan Day',
     'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]},
  {'id': 31,
   'Year': 1996,
   'Title': 'The Green Mile',
   'handle': 'the-green-mile',
   'Publisher': 'Signet Books',
   'ISBN': '978-0-451-19049-9978-0-451-19052-9978-0-451-19054-3978-0-451-19055-0978-0-451-19056-7978-0-451-19057-4',
   'Pages': 400,
   'Notes': ['Winner, Bram Stoker Award, 1997',
    'Runner-up (8th place), Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.660Z',
   'villains': [{'name': 'Percy Wetmore',
     'url': 'https://stephen-king-api.onrender.com/api/villain/111'},
    {'name': 'William Wharton',
     'url': 'https://stephen-king-api.onrender.com/api/villain/112'}]},
  {'id': 32,
   'Year': 1996,
   'Title': 'Desperation',
   'handle': 'desperation',
   'Publisher': 'Viking',
   'ISBN': '978-0-670-86836-0',
   'Pages': 704,
   'Notes': ['Twin novel of The Regulators',
    'Winner, Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'],
   'created_at': '2023-11-13T23:48:51.784Z',
   'villains': []},
  {'id': 33,
   'Year': 1996,
   'Title': 'The Regulators',
   'handle': 'the-regulators',
   'Publisher': 'Dutton',
   'ISBN': '978-0-525-94190-3',
   'Pages': 480,
   'Notes': ['Published under pseudonym Richard Bachman',
    'Twin novel of Desperation'],
   'created_at': '2023-11-13T23:48:51.900Z',
   'villains': []},
  {'id': 34,
   'Year': 1997,
   'Title': 'The Dark Tower IV: Wizard and Glass',
   'handle': 'the-dark-tower-iv-wizard-and-glass',
   'Publisher': 'Grant',
   'ISBN': '978-1-880418-38-3',
   'Pages': 787,
   'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1998',
    'Runner-up (6th place), Locus Award for Best Art Book, 1998[2]'],
   'created_at': '2023-11-13T23:48:52.019Z',
   'villains': [{'name': 'Blaine the Mono',
     'url': 'https://stephen-king-api.onrender.com/api/villain/3'},
    {'name': 'Cordelia Delgado',
     'url': 'https://stephen-king-api.onrender.com/api/villain/24'},
    {'name': 'Rhea Dubativo',
     'url': 'https://stephen-king-api.onrender.com/api/villain/32'},

In [7]:
import pandas as pd
df = pd.json_normalize(json_data["data"])

In [8]:
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
58,59,2018,The Outsider,the-outsider,Scribner,978-1-50118-098-9,576,"[First novel in the Holly Gibney Series, Runne...",2023-11-13T23:48:55.165Z,"[{'name': 'The Outsider (Creature)', 'url': 'h..."
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]

In [9]:
df = df[['id','Year','Title','ISBN']]

In [10]:
df

    id  Year          Title               ISBN
0    1  1974         Carrie  978-0-385-08695-0
1    2  1975    Salem's Lot  978-0-385-00751-1
2    3  1977    The Shining  978-0-385-12167-5
3    4  1977           Rage  978-0-451-07645-8
4    5  1978      The Stand  978-0-385-12168-2
..  ..   ...            ...                ...
58  59  2018   The Outsider  978-1-50118-098-9
59  60  2018      Elevation  978-1-98210-231-9
60  61  2019  The Institute  978-1-98211-056-7
61  62  2021          Later  978-1-78909-649-1
62  63  2021  Billy Summers  978-1-982-17361-6

[63 rows x 4 columns]

### Practising API

In [18]:
import requests
URL = "https://dog.ceo/api/breeds/image/random"
res = requests.get(URL)

In [19]:
print(res.status_code)

200

In [20]:
print(res.headers)

{'Date': 'Sun, 14 Dec 2025 01:52:47 GMT', 'Content-Type': 'application/json', 'Content-Length': '111', 'Connection': 'keep-alive', 'Server': 'cloudflare', 'X-Powered-By': 'PHP/8.3.28', 'Cache-Control': 'no-cache, private', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Via': '1.1 varnish (Varnish/6.3), 1.1 varnish (Varnish/6.3)', 'X-Cache-Hits': '0', 'X-Cache': 'MISS', 'Accept-Ranges': 'bytes', 'Age': '0', 'Vary': 'Accept-Encoding', 'Nel': '{"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}', 'cf-cache-status': 'DYNAMIC', 'Speculation-Rules': '"/cdn-cgi/speculation"', 'Report-To': '{"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=IWFMNIV08x5MbYPDOUtNumEYhEipI8%2BiOdExJDXLuLMNxhj1aW7UY25ngdMD%2FpLZRSZa5AjHotamEDW%2F1s2P0Hm%2B4%2FxvKoBi7uU%2Bamf7mOPH27c%3D"}]}', 'CF-RAY': '9ada105a4a08d204-AMS', 'alt-svc': 'h3=":443"; ma=86400'}

In [21]:
json_res = res.json()
json_res

{'message': 'https://images.dog.ceo/breeds/poodle-miniature/n02113712_335.jpg',
 'status': 'success'}

In [31]:
import requests
URL = "https://stephen-king-api.onrender.com/api/villains"
response = requests.get(URL)

In [32]:
print(response.status_code)

200

In [33]:
print(response.headers)

{'Date': 'Sun, 14 Dec 2025 02:03:31 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'access-control-allow-origin': '*', 'etag': 'W/"9acd-3vD+Z+/Y0V7jIXyafapdZZE2Wuk"', 'rndr-id': '8e4703c0-7f29-44e0', 'vary': 'Accept-Encoding', 'x-powered-by': 'Express', 'x-render-origin-server': 'Render', 'cf-cache-status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '9ada20088fb934be-BOM', 'alt-svc': 'h3=":443"; ma=86400'}

In [34]:
json_data = response.json()
json_data

{'data': [{'id': 1,
   'name': 'Bob Anderson',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Pownal residents',
    'Yarmouth residents',
    'Residents of Maine',
    'Villains',
    'Crime'],
   'created_at': '2023-11-13T23:49:22.390Z',
   'books': [],
   'shorts': [{'title': 'A Good Marriage',
     'url': 'https://stephen-king-api.onrender.com/api/book/180'}]},
  {'id': 2,
   'name': 'Kurt Barlow',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 2,
   'notes': ['Characters',
    "Jerusalem's Lot residents",
    'Residents of Maine',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:22.625Z',
   'books': [{'title': "Salem's Lot",
     'url': 'https://stephen-king-api.onrender.com/api/book/2'}],
   'shorts': []},
  {'id': 3,
   'name': 'Blaine the Mono',
   'gender': None,
   'status': 'Deceased',
   'types_id': 6,
   'notes': ['Characters',
    'Unsourced quotes',
    'The Dark Tower',
    'Villains',
    'Machines',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:22.743Z',
   'books': [{'title': 'The Dark Tower IV: Wizard and Glass',
     'url': 'https://stephen-king-api.onrender.com/api/book/34'},
    {'title': 'The Dark Tower III: The Waste Lands',
     'url': 'https://stephen-king-api.onrender.com/api/book/25'}],
   'shorts': []},
  {'id': 4,
   'name': 'Tina Blake',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Ewen High School students',
    'Residents of Maine',
    'Chamberlain residents',
    'Bullies',
    'Name-continuity',
    'Lovers',
    'Bate High School students',
    'Villains',
    'Antagonists',
    'Carrie'],
   'created_at': '2023-11-13T23:49:22.968Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 5,
   'name': 'Malachai Boardman',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Stubs', 'Characters', 'Villains', 'Antagonists'],
   'created_at': '2023-11-13T23:49:23.089Z',
   'books': [],
   'shorts': [{'title': 'Children of the Corn',
     'url': 'https://stephen-king-api.onrender.com/api/book/53'}]},
  {'id': 6,
   'name': 'James Boon',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs', 'Characters', 'Villains', "Jerusalem's Lot residents"],
   'created_at': '2023-11-13T23:49:23.203Z',
   'books': [],
   'shorts': [{'title': "Jerusalem's Lot",
     'url': 'https://stephen-king-api.onrender.com/api/book/58'}]},
  {'id': 7,
   'name': 'Henry Bowers',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Unsourced quotes',
    'Bullies',
    'Characters with mental illness',
    'Derry residents',
    'IT',
    'Residents of Maine',
    'Seekers of vengeance',
    'Villains',
    'Leaders',
    'Gang Leaders',
    'Slashers',
    'Victims',
    'LGBT',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:23.320Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 8,
   'name': 'Butch Bowers',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Unsourced quotes',
    'Derry residents',
    'Residents of Maine',
    'IT',
    'Antagonists',
    'Villains',
    'Bullies',
    'Characters with mental illness',
    'Spouses'],
   'created_at': '2023-11-13T23:49:23.438Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 9,
   'name': 'Greta Bowie',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Derry residents',
    'IT',
    'Residents of Maine',
    'Bullies',
    'Leaders',
    'Antagonists',
    'Status dependant on version',
    'Villains'],
   'created_at': '2023-11-13T23:49:23.561Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 10,
   'name': 'Marten Broadcloak',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Gilead residents',
    'The Dark Tower',
    'Residents of All-world',
    'Villains',
    'Lovers',
    'Multiverse'],
   'created_at': '2023-11-13T23:49:23.690Z',
   'books': [{'title': 'The Dark Tower: The Gunslinger',
     'url': 'https://stephen-king-api.onrender.com/api/book/12'}],
   'shorts': []},
  {'id': 11,
   'name': 'Christine (car)',
   'gender': 'Female',
   'status': 'Alive',
   'types_id': 6,
   'notes': ['Characters',
    'Objects',
    'Villains',
    'Christine',
    'Demonic items',
    'Antagonists',
    'Ghosts',
    'Murderers',
    'Seekers of vengeance'],
   'created_at': '2023-11-13T23:49:23.805Z',
   'books': [{'title': 'Christine',
     'url': 'https://stephen-king-api.onrender.com/api/book/13'}],
   'shorts': []},
  {'id': 12,
   'name': 'Isaac Chroner',
   'gender': None,
   'status': 'Deceased',
   'types_id': 6,
   'notes': ['Characters', 'Villains', 'Antagonists'],
   'created_at': '2023-11-13T23:49:23.918Z',
   'books': [],
   'shorts': [{'title': 'Children of the Corn',
     'url': 'https://stephen-king-api.onrender.com/api/book/53'}]},
  {'id': 13,
   'name': 'Winston Church',
   'gender': None,
   'status': 'Deceased',
   'types_id': 8,
   'notes': ['Characters',
    'Cats',
    'Villains',
    'Pet Sematary',
    'Status dependant on version',
    'Revived'],
   'created_at': '2023-11-13T23:49:24.039Z',
   'books': [{'title': 'Pet Sematary',
     'url': 'https://stephen-king-api.onrender.com/api/book/14'}],
   'shorts': []},
  {'id': 14,
   'name': 'Cindi',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Ewen High School students',
    'Unknown fates',
    'Chamberlain residents',
    'Residents of Maine',
    'Bate High School students',
    'Bullies',
    'Villains',
    'Name-continuity',
    'Antagonists',
    'Victims',
    'Carrie'],
   'created_at': '2023-11-13T23:49:24.159Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 15,
   'name': 'Gage Creed',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 3,
   'notes': ['Characters',
    'Villains',
    'Pet Sematary',
    'Status dependant on version',
    'Revived',
    'Antagonists',
    'Residents of Maine'],
   'created_at': '2023-11-13T23:49:24.285Z',
   'books': [{'title': 'Pet Sematary',
     'url': 'https://stephen-king-api.onrender.com/api/book/14'}],
   'shorts': []},
  {'id': 16,
   'name': 'Myra Crewes',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Chamberlain residents',
    'Residents of Maine',
    'Villains',
    'Bullies',
    'Ewen High School students',
    'Unknown fates',
    'Bate High School students',
    'Antagonists',
    'Victims',
    'Carrie'],
   'created_at': '2023-11-13T23:49:24.403Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 17,
   'name': 'Crimson King',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 3,
   'notes': ['Characters',
    'The Dark Tower',
    'Multiverse',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:24.525Z',
   'books': [{'title': 'Insomnia',
     'url': 'https://stephen-king-api.onrender.com/api/book/29'},
    {'title': 'The Dark Tower: The Gunslinger',
     'url': 'https://stephen-king-api.onrender.com/api/book/12'},
    {'title': 'Black House',
     'url': 'https://stephen-king-api.onrender.com/api/book/38'},
    {'title': 'The Dark Tower VII: The Dark Tower',
     'url': 'https://stephen-king-api.onrender.com/api/book/42'}],
   'shorts': []},
  {'id': 18,
   'name': 'Victor Criss',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Unsourced quotes',
    'Bullies',
    'Derry residents',
    'Residents of Maine',
    'IT',
    'Villains',
    'Antagonists',
    'Victims',
    'Status dependant on version'],
   'created_at': '2023-11-13T23:49:24.664Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 19,
   'name': 'Cujo',
   'gender': None,
   'status': 'Deceased',
   'types_id': 8,
   'notes': ['Characters',
    'Dogs',
    'Characters with mental illness',
    'Castle Rock residents',
    'Residents of Maine',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:24.799Z',
   'books': [{'title': 'Cujo',
     'url': 'https://stephen-king-api.onrender.com/api/book/10'}],
   'shorts': []},
  {'id': 20,
   'name': 'Arnie Cunningham',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Unsourced quotes',
    'Seekers of vengeance',
    'Lovers',
    'Christine',
    'Villains',
    'Antagonists',
    'Victims',
    'Heroes',
    'Protagonists'],
   'created_at': '2023-11-13T23:49:24.927Z',
   'books': [{'title': 'Christine',
     'url': 'https://stephen-king-api.onrender.com/api/book/13'}],
   'shorts': []},
  {'id': 21,
   'name': 'Dandelo',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 2,
   'notes': ['Characters', 'Villains'],
   'created_at': '2023-11-13T23:49:25.057Z',
   'books': [{'title': 'The Dark Tower VII: The Dark Tower',
     'url': 'https://stephen-king-api.onrender.com/api/book/42'}],
   'shorts': []},
  {'id': 22,
   'name': 'Norman Daniels',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Unsourced quotes',
    'Police',
    'Antagonists',
    'Villains',
    'Murderers'],
   'created_at': '2023-11-13T23:49:25.174Z',
   'books': [{'title': 'Rose Madder',
     'url': 'https://stephen-king-api.onrender.com/api/book/30'}],
   'shorts': []},
  {'id': 23,
   'name': 'Susan Day',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Stubs', 'Characters', 'Villains'],
   'created_at': '2023-11-13T23:49:25.311Z',
   'books': [{'title': 'Rose Madder',
     'url': 'https://stephen-king-api.onrender.com/api/book/30'},
    {'title': 'Insomnia',
     'url': 'https://stephen-king-api.onrender.com/api/book/29'}],
   'shorts': []},
  {'id': 24,
   'name': 'Cordelia Delgado',
   'gender': 'Female',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Characters', 'Villains', 'The Dark Tower', 'Antagonists'],
   'created_at': '2023-11-13T23:49:25.430Z',
   'books': [{'title': 'The Dark Tower IV: Wizard and Glass',
     'url': 'https://stephen-king-api.onrender.com/api/book/34'}],
   'shorts': []},
  {'id': 25,
   'name': 'Billy deLois',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Chamberlain residents',
    'Residents of Maine',
    'Unknown fates',
    'Ewen High School students',
    'Bullies',
    'Villains',
    'Antagonists',
    'Carrie'],
   'created_at': '2023-11-13T23:49:25.546Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 26,
   'name': 'Horace M. Derwent',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 7,
   'notes': ['Stubs',
    'Characters',
    'Appearances',
    'The Shining',
    'Villains',
    'Ghosts',
    'LGBT'],
   'created_at': '2023-11-13T23:49:25.758Z',
   'books': [{'title': 'The Shining',
     'url': 'https://stephen-king-api.onrender.com/api/book/3'}],
   'shorts': []},
  {'id': 27,
   'name': 'Mordred Deschain',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 3,
   'notes': ['Characters',
    'ESPers',
    'The Dark Tower',
    'Multiverse',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:25.873Z',
   'books': [{'title': 'The Dark Tower VII: The Dark Tower',
     'url': 'https://stephen-king-api.onrender.com/api/book/42'}],
   'shorts': []},
  {'id': 28,
   'name': 'Bogs Diamond',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs', 'Characters', 'Villains', 'Leaders'],
   'created_at': '2023-11-13T23:49:25.992Z',
   'books': [],
   'shorts': [{'title': 'Rita Hayworth and Shawshank Redemption',
     'url': 'https://stephen-king-api.onrender.com/api/book/86'}]},
  {'id': 29,
   'name': 'Frank Dodd',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Police',
    'Murderers',
    'Villains',
    'Government employees',
    'Characters with mental illness',
    'The Dead Zone',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:26.115Z',
   'books': [{'title': 'The Dead Zone',
     'url': 'https://stephen-king-api.onrender.com/api/book/7'}],
   'shorts': []},
  {'id': 30,
   'name': 'Henrietta Dodd',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters', 'The Dead Zone', 'Villains'],
   'created_at': '2023-11-13T23:49:26.240Z',
   'books': [{'title': 'The Dead Zone',
     'url': 'https://stephen-king-api.onrender.com/api/book/7'}],
   'shorts': []},
  {'id': 31,
   'name': 'Rose the Hat',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Doctor Sleep',
    'Villains',
    'Harassers',
    'Murderers',
    'LGBT',
    'Bullies'],
   'created_at': '2023-11-13T23:49:26.355Z',
   'books': [{'title': 'Doctor Sleep',
     'url': 'https://stephen-king-api.onrender.com/api/book/52'}],
   'shorts': []},
  {'id': 32,
   'name': 'Rhea Dubativo',
   'gender': 'Female',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Hambry residents',
    'The Dark Tower',
    'Residents of All-world',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:26.474Z',
   'books': [{'title': 'The Dark Tower IV: Wizard and Glass',
     'url': 'https://stephen-king-api.onrender.com/api/book/34'}],
   'shorts': []},
  {'id': 33,
   'name': 'Kurt Dussander',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Stubs', 'Characters', 'Villains'],
   'created_at': '2023-11-13T23:49:26.598Z',
   'books': [],
   'shorts': [{'title': 'Apt Pupil',
     'url': 'https://stephen-king-api.onrender.com/api/book/83'}]},
  {'id': 34,
   'name': 'Donald Merwin Elbert',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Villains',
    'Antagonists',
    'The Stand',
    'Characters with mental illness'],
   'created_at': '2023-11-13T23:49:26.707Z',
   'books': [{'title': 'The Stand',
     'url': 'https://stephen-king-api.onrender.com/api/book/5'}],
   'shorts': []},
  {'id': 35,
   'name': 'Marcia Fadden',
   'gender': 'Female',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Characters',
    'Derry residents',
    'IT',
    'Residents of Maine',
    'Villains',
    'Bullies'],
   'created_at': '2023-11-13T23:49:26.820Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 36,
   'name': 'John Farson',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'The Dark Tower',
    'Villains',
    'Antagonists'],
   'created_at': '2023-11-13T23:49:26.944Z',
   'books': [{'title': 'The Dark Tower IV: Wizard and Glass',
     'url': 'https://stephen-king-api.onrender.com/api/book/34'}],
   'shorts': []},
  {'id': 37,
   'name': 'Randall Flagg',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 3,
   'notes': ['Characters',
    'The Stand',
    'The Dark Tower',
    'Villains',
    'Bullies',
    'Leaders',
    'Revived',
    'Antagonists',
    'Meta-fiction',
    'Dystopian'],
   'created_at': '2023-11-13T23:49:27.063Z',
   'books': [{'title': 'The Stand',
     'url': 'https://stephen-king-api.onrender.com/api/book/5'},
    {'title': 'The Eyes of the Dragon',
     'url': 'https://stephen-king-api.onrender.com/api/book/17'},
    {'title': 'The Long Walk',
     'url': 'https://stephen-king-api.onrender.com/api/book/6'},
    {'title': 'The Dark Tower: The Gunslinger',
     'url': 'https://stephen-king-api.onrender.com/api/book/12'},
    {'title': 'The Dark Tower VII: The Dark Tower',
     'url': 'https://stephen-king-api.onrender.com/api/book/42'},
    {'title': 'The Dark Tower IV: Wizard and Glass',
     'url': 'https://stephen-king-api.onrender.com/api/book/34'},
    {'title': 'The Dark Tower III: The Waste Lands',
     'url': 'https://stephen-king-api.onrender.com/api/book/25'}],
   'shorts': []},
  {'id': 38,
   'name': 'Kenny Garson',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Ewen High School students',
    'Chamberlain residents',
    'Bullies',
    'Residents of Maine',
    'Villains',
    'Victims',
    'Bate High School students',
    'Unknown fates',
    'Antagonists',
    'Carrie'],
   'created_at': '2023-11-13T23:49:27.183Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 39,
   'name': 'John Garton',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Bullies',
    'Derry residents',
    'Residents of Maine',
    'IT',
    'Antagonists',
    'Villains',
    'Teachers'],
   'created_at': '2023-11-13T23:49:27.301Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 40,
   'name': 'Leland Gaunt',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 6,
   'notes': ['Characters', 'Villains', 'Castle Rock residents', 'Antagonists'],
   'created_at': '2023-11-13T23:49:27.414Z',
   'books': [{'title': 'Needful Things',
     'url': 'https://stephen-king-api.onrender.com/api/book/26'}],
   'shorts': []},
  {'id': 41,
   'name': 'Gerald Burlingame',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Antagonists',
    'Spouses',
    'Villains',
    "Gerald's Game",
    'Residents of Maine'],
   'created_at': '2023-11-13T23:49:27.535Z',
   'books': [{'title': "Gerald's Game",
     'url': 'https://stephen-king-api.onrender.com/api/book/27'}],
   'shorts': []},
  {'id': 42,
   'name': 'The Gladiators',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 5,
   'notes': ['Characters', 'Villains'],
   'created_at': '2023-11-13T23:49:27.646Z',
   'books': [{'title': 'The Running Man',
     'url': 'https://stephen-king-api.onrender.com/api/book/11'}],
   'shorts': []},
  {'id': 43,
   'name': 'Peter Gordon',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,
   'notes': ['Stubs',
    'Characters',
    'Derry residents',
    'Residents of Maine',
    'Bullies',
    'Antagonists',
    'Victims',
    'IT',
    'Villains'],
   'created_at': '2023-11-13T23:49:27.764Z',
   'books': [{'title': 'It',
     'url': 'https://stephen-king-api.onrender.com/api/book/19'}],
   'shorts': []},
  {'id': 44,
   'name': 'Mary Lila Grace',
   'gender': 'Female',
   'status': 'Deceased',
   'types_id': 1,
   'notes': ['Characters',
    'Ewen High School students',
    'Chamberlain residents',
    'Bullies',
    'Villains',
    'Lovers',
    'Carrie'],
   'created_at': '2023-11-13T23:49:27.890Z',
   'books': [{'title': 'Carrie',
     'url': 'https://stephen-king-api.onrender.com/api/book/1'}],
   'shorts': []},
  {'id': 45,
   'name': 'Delbert Grady',
   'gender': 'Male',
   'status': 'Deceased',
   'types_id': 7,
   'notes': ['Characters',
    'Spouses',
    'Lovers',
    'Ghosts',
    'The Shining',
    'Villains',
    'Harassers'],
   'created_at': '2023-11-13T23:49:28.006Z',
   'books': [{'title': 'The Shining',
     'url': 'https://stephen-king-api.onrender.com/api/book/3'}],
   'shorts': []},
  {'id': 46,
   'name': 'Byron Hadley',
   'gender': 'Male',
   'status': 'Alive',
   'types_id': 1,

In [36]:
import pandas as pd
df = pd.json_normalize(json_data['data'])

In [37]:
df

,id,name,gender,status,types_id,notes,created_at,books,shorts
0,1,Bob Anderson,Male,Deceased,1,"[Stubs, Characters, Pownal residents, Yarmouth...",2023-11-13T23:49:22.390Z,[],"[{'title': 'A Good Marriage', 'url': 'https://..."
1,2,Kurt Barlow,Male,Deceased,2,"[Characters, Jerusalem's Lot residents, Reside...",2023-11-13T23:49:22.625Z,"[{'title': 'Salem's Lot', 'url': 'https://step...",[]
2,3,Blaine the Mono,None,Deceased,6,"[Characters, Unsourced quotes, The Dark Tower,...",2023-11-13T23:49:22.743Z,[{'title': 'The Dark Tower IV: Wizard and Glas...,[]
3,4,Tina Blake,Female,Deceased,1,"[Characters, Ewen High School students, Reside...",2023-11-13T23:49:22.968Z,"[{'title': 'Carrie', 'url': 'https://stephen-k...",[]
4,5,Malachai Boardman,Male,Deceased,1,"[Stubs, Characters, Villains, Antagonists]",2023-11-13T23:49:23.089Z,[],"[{'title': 'Children of the Corn', 'url': 'htt..."
...,...,...,...,...,...,...,...,...,...
110,111,Percy Wetmore,Male,Deceased,1,"[Characters, The Green Mile, Villains, Antagon...",2023-11-13T23:49:36.274Z,"[{'title': 'The Green Mile', 'url': 'https://s...",[]
111,112,William Wharton,Male,Deceased,1,"[Stubs, Characters, Villains, The Green Mile v...",2023-11-13T23:49:36.386Z,"[{'title': 'The Green Mile', 'url': 'https://s...",[]
112,113,Margaret White,Female,Deceased,1,"[Characters, Unsourced quotes, Spouses, Widows...",2023-11-13T23:49:36.505Z,"[{'title': 'Carrie', 'url': 'https://stephen-k...",[]
113,114,Annie Wilkes,Female,Deceased,1,"[Characters, Villains, Characters with mental ...",2023-11-13T23:49:36.623Z,"[{'title': 'Misery', 'url': 'https://stephen-k...",[]
114,115,Tim Youngblood,Male,Alive,1,"[Stubs, Characters, Villains]",2023-11-13T23:49:36.745Z,[],[{'title': 'Rita Hayworth and Shawshank Redemp...

In [39]:
filter_df = df[['id','name','gender','shorts']]
filter_df

,id,name,gender,shorts
0,1,Bob Anderson,Male,"[{'title': 'A Good Marriage', 'url': 'https://..."
1,2,Kurt Barlow,Male,[]
2,3,Blaine the Mono,None,[]
3,4,Tina Blake,Female,[]
4,5,Malachai Boardman,Male,"[{'title': 'Children of the Corn', 'url': 'htt..."
...,...,...,...,...
110,111,Percy Wetmore,Male,[]
111,112,William Wharton,Male,[]
112,113,Margaret White,Female,[]
113,114,Annie Wilkes,Female,[]
114,115,Tim Youngblood,Male,[{'title': 'Rita Hayworth and Shawshank Redemp...

In [40]:
import requests
URL = "https://www.scrapethissite.com/pages/simple/"
res = requests.get(URL)

In [42]:
print(res.status_code)

200

In [ ]:
if res.status_code == 200:
    print(res.headers)

with open('scraped_data/data1.html','w') as f:
    f.write(res.text) # single page scraped

{'Date': 'Sun, 14 Dec 2025 02:43:20 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=6VwQW2NifAgTy7AythKPvHZdWkkOOUjjoIfkWHvSUuo%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1765680199"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=6VwQW2NifAgTy7AythKPvHZdWkkOOUjjoIfkWHvSUuo%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1765680199"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'gzip', 'CF-RAY': '9ada5a5e0ba6cdd9-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

### Using beautifulsoup (BS4)

In [53]:
!pip install lxml

Requirement already satisfied: lxml in d:\aiml prime\venv\lib\site-packages (6.0.2)

In [55]:
from bs4 import BeautifulSoup
with open("scraped_data/data1.html","r") as  f:
    html_content = f.read()

soup = BeautifulSoup(html_content,"html.parser")

In [56]:
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping
    </title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                            Scrape This Site
                        </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                            Sandbox
                        </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                            Lessons
                        </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                            FAQ
                        </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                            Login
                        </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
        var path = document.location.pathname;
        var tab = undefined;
        if (path === "/") {
            tab = document.querySelector("#nav-homepage");
        } else if (path.indexOf("/faq/") === 0) {
            tab = document.querySelector("#nav-faq");
        } else if (path.indexOf("/lessons/") === 0) {
            tab = document.querySelector("#nav-lessons");
        } else if (path.indexOf("/pages/") === 0) {
            tab = document.querySelector("#nav-sandbox");
        } else if (path.indexOf("/login/") === 0) {
            tab = document.querySelector("#nav-login");
        }
        tab.classList.add("active")
    </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those
                            just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about
                            each country. Then, build a simple web scraper that makes a request to this page, parses the
                            HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video
                                lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                            Data via
                            <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

In [90]:
## bs4 methods
all_h3 = soup.find_all("h3")
all_countires = []

for h3 in all_h3:
    name = print(h3.get_text(strip=True))
    # print(h3.find_parent("div")['class'])

    population = h3.find_next("div").select("span.country-population")[0].get_text(strip=True)

    #print(h3.find_next("div").select_one("span.country-population").get_text(strip=True))
    
    all_countires.append([name,population])

Andorra
United Arab Emirates
Afghanistan
Antigua and Barbuda
Anguilla
Albania
Armenia
Angola
Antarctica
Argentina
American Samoa
Austria
Australia
Aruba
Åland
Azerbaijan
Bosnia and Herzegovina
Barbados
Bangladesh
Belgium
Burkina Faso
Bulgaria
Bahrain
Burundi
Benin
Saint Barthélemy
Bermuda
Brunei
Bolivia
Bonaire
Brazil
Bahamas
Bhutan
Bouvet Island
Botswana
Belarus
Belize
Canada
Cocos [Keeling] Islands
Democratic Republic of the Congo
Central African Republic
Republic of the Congo
Switzerland
Ivory Coast
Cook Islands
Chile
Cameroon
China
Colombia
Costa Rica
Cuba
Cape Verde
Curacao
Christmas Island
Cyprus
Czech Republic
Germany
Djibouti
Denmark
Dominica
Dominican Republic
Algeria
Ecuador
Estonia
Egypt
Western Sahara
Eritrea
Spain
Ethiopia
Finland
Fiji
Falkland Islands
Micronesia
Faroe Islands
France
Gabon
United Kingdom
Grenada
Georgia
French Guiana
Guernsey
Ghana
Gibraltar
Greenland
Gambia
Guinea
Guadeloupe
Equatorial Guinea
Greece
South Georgia and the South Sandwich Islands
Guatemala
Guam
Guinea-Bissau
Guyana
Hong Kong
Heard Island and McDonald Islands
Honduras
Croatia
Haiti
Hungary
Indonesia
Ireland
Israel
Isle of Man
India
British Indian Ocean Territory
Iraq
Iran
Iceland
Italy
Jersey
Jamaica
Jordan
Japan
Kenya
Kyrgyzstan
Cambodia
Kiribati
Comoros
Saint Kitts and Nevis
North Korea
South Korea
Kuwait
Cayman Islands
Kazakhstan
Laos
Lebanon
Saint Lucia
Liechtenstein
Sri Lanka
Liberia
Lesotho
Lithuania
Luxembourg
Latvia
Libya
Morocco
Monaco
Moldova
Montenegro
Saint Martin
Madagascar
Marshall Islands
Macedonia
Mali
Myanmar [Burma]
Mongolia
Macao
Northern Mariana Islands
Martinique
Mauritania
Montserrat
Malta
Mauritius
Maldives
Malawi
Mexico
Malaysia
Mozambique
Namibia
New Caledonia
Niger
Norfolk Island
Nigeria
Nicaragua
Netherlands
Norway
Nepal
Nauru
Niue
New Zealand
Oman
Panama
Peru
French Polynesia
Papua New Guinea
Philippines
Pakistan
Poland
Saint Pierre and Miquelon
Pitcairn Islands
Puerto Rico
Palestine
Portugal
Palau
Paraguay
Qatar
Réunion
Romania
Serbia
Russia
Rwanda
Saudi Arabia
Solomon Islands
Seychelles
Sudan
Sweden
Singapore
Saint Helena
Slovenia
Svalbard and Jan Mayen
Slovakia
Sierra Leone
San Marino
Senegal
Somalia
Suriname
South Sudan
São Tomé and Príncipe
El Salvador
Sint Maarten
Syria
Swaziland
Turks and Caicos Islands
Chad
French Southern Territories
Togo
Thailand
Tajikistan
Tokelau
East Timor
Turkmenistan
Tunisia
Tonga
Turkey
Trinidad and Tobago
Tuvalu
Taiwan
Tanzania
Ukraine
Uganda
U.S. Minor Outlying Islands
United States
Uruguay
Uzbekistan
Vatican City
Saint Vincent and the Grenadines
Venezuela
British Virgin Islands
U.S. Virgin Islands
Vietnam
Vanuatu
Wallis and Futuna
Samoa
Kosovo
Yemen
Mayotte
South Africa
Zambia
Zimbabwe

In [91]:
import pandas as pd
df = pd.DataFrame(all_countires,columns=["Name","Population"])

In [92]:
df

     Name Population
0    None      84000
1    None    4975593
2    None   29121286
3    None      86754
4    None      13254
..    ...        ...
245  None   23495361
246  None     159042
247  None   49000000
248  None   13460305
249  None   11651858

[250 rows x 2 columns]

In [94]:
df.to_csv("cleaned_data/data.csv",index=False)