#### ML Concept Revision

In [1]:
import pandas as pd
data = {
     'name':['alex','kush','ankit','kaveri'],
     'age':[21,None,22,None],
     'salary':[80000,70000,50000,45000]
}

df = pd.DataFrame(data)
print("Original DataFrame")
print(df)

Original DataFrame
     name   age  salary
0    alex  21.0   80000
1    kush   NaN   70000
2   ankit  22.0   50000
3  kaveri   NaN   45000

In [2]:
print(df.isnull().sum())

name      0
age       2
salary    0
dtype: int64

In [3]:
df_drop = df.dropna()

In [4]:
print(df_drop)

    name   age  salary
0   alex  21.0   80000
2  ankit  22.0   50000

- Data Preproccesing & Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

df = pd.read_csv("data.csv")
df

      Name  Gender       City Passed
0     Aman    Male      Delhi    Yes
1    Priya  Female     Mumbai    Yes
2    Rahul    Male  Bangalore     No
3   Anjali  Female     Mumbai    Yes
4     Ravi    Male      Delhi    Yes
5    Meera  Female    Chennai     No
6    Arjun    Male  Bangalore    Yes
7     Neha  Female      Delhi    Yes
8    Imran    Male    Chennai     No
9    Sneha  Female     Mumbai    Yes
10     Raj    Male    Chennai    Yes
11   Divya  Female      Delhi     No
12   Kabir    Male     Mumbai    Yes
13  Simran  Female  Bangalore    Yes
14   Karan    Male      Delhi     No
15   Pooja  Female     Mumbai    Yes
16  Rakesh    Male    Chennai    Yes
17    Isha  Female      Delhi     No
18   Rohit    Male      Delhi    Yes
19   Deepa  Female  Bangalore    Yes

In [7]:
df_label = df.copy()

le = LabelEncoder()
df_label['Gender_Encoded'] = le.fit_transform(df_label['Gender'])
df_label['Passed_Encoded'] = le.fit_transform(df_label['Passed'])

print("Label Encoded Data")
print(df_label[['Name','Gender','Gender_Encoded','Passed_Encoded']])

Label Encoded Data
      Name  Gender  Gender_Encoded  Passed_Encoded
0     Aman    Male               1               1
1    Priya  Female               0               1
2    Rahul    Male               1               0
3   Anjali  Female               0               1
4     Ravi    Male               1               1
5    Meera  Female               0               0
6    Arjun    Male               1               1
7     Neha  Female               0               1
8    Imran    Male               1               0
9    Sneha  Female               0               1
10     Raj    Male               1               1
11   Divya  Female               0               0
12   Kabir    Male               1               1
13  Simran  Female               0               1
14   Karan    Male               1               0
15   Pooja  Female               0               1
16  Rakesh    Male               1               1
17    Isha  Female               0               0
18   Rohit    Male               1               1
19   Deepa  Female               0               1

In [8]:
df_encoded = pd.get_dummies(df_label,columns=["City"])
print(df_encoded)

      Name  Gender Passed  Gender_Encoded  Passed_Encoded  City_Bangalore  \
0     Aman    Male    Yes               1               1           False
1    Priya  Female    Yes               0               1           False
2    Rahul    Male     No               1               0            True
3   Anjali  Female    Yes               0               1           False
4     Ravi    Male    Yes               1               1           False
5    Meera  Female     No               0               0           False
6    Arjun    Male    Yes               1               1            True
7     Neha  Female    Yes               0               1           False
8    Imran    Male     No               1               0           False
9    Sneha  Female    Yes               0               1           False
10     Raj    Male    Yes               1               1           False
11   Divya  Female     No               0               0           False
12   Kabir    Male    Yes               1               1           False
13  Simran  Female    Yes               0               1            True
14   Karan    Male     No               1               0           False
15   Pooja  Female    Yes               0               1           False
16  Rakesh    Male    Yes               1               1           False
17    Isha  Female     No               0               0           False
18   Rohit    Male    Yes               1               1           False
19   Deepa  Female    Yes               0               1            True

    City_Chennai  City_Delhi  City_Mumbai
0          False        True        False
1          False       False         True
2          False       False        False
3          False       False         True
4          False        True        False
5           True       False        False
6          False       False        False
7          False        True        False
8           True       False        False
9          False       False         True
10          True       False        False
11         False        True        False
12         False       False         True
13         False       False        False
14         False        True        False
15         False       False         True
16          True       False        False
17         False        True        False
18         False        True        False
19         False       False        False

- Standard Scaler & Minmax Scaler

In [ ]:
# scaler = StandardScaler()
# X_scaled = scaler.fit_transform()

# scaler = MinMaxScaler()
# x_s1caled = scaler.fit_transform()

In [20]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split

data = {
     'Study_Hrs':[1,2,3,4,5],
     'Test_Scr':[40,50,60,90,100]
}
df = pd.DataFrame(data)

In [21]:
df

   Study_Hrs  Test_Scr
0          1        40
1          2        50
2          3        60
3          4        90
4          5       100

In [22]:
## Standard Scaler
standard_scaler = StandardScaler()
standard_scaled = standard_scaler.fit_transform(df)
print(pd.DataFrame(standard_scaled,columns=['Study_Hrs','Test_Scr']))

   Study_Hrs  Test_Scr
0  -1.414214 -1.209416
1  -0.707107 -0.777482
2   0.000000 -0.345547
3   0.707107  0.950255
4   1.414214  1.382189

In [23]:
## Minmax Scaler
standard_scaler = MinMaxScaler()
standard_scaled = standard_scaler.fit_transform(df)
print(pd.DataFrame(standard_scaled,columns=['Study_Hrs','Test_Scr']))

   Study_Hrs  Test_Scr
0       0.00  0.000000
1       0.25  0.166667
2       0.50  0.333333
3       0.75  0.833333
4       1.00  1.000000

In [24]:
X = df[['Study_Hrs']]
Y = df[['Test_Scr']]

X_Train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [25]:
print(X_Train)

   Study_Hrs
4          5
2          3
0          1
3          4

In [26]:
print(X_test)

   Study_Hrs
1          2

#### Supervised Learning Algos

- Linear Regression

In [4]:
from sklearn.linear_model import LinearRegression
X = [[1],[2],[3],[4],[5]]
Y = [40,50,60,78,90]

model = LinearRegression()
model.fit(X,Y)

hrs = float(input('enter your study hrs: '))
predicted_marks = model.predict([[hrs]])
print(f"Based on your hours {hrs} you scored around {predicted_marks}")

Based on your hours 3.0 you scored around [63.6]

- Logistic Regression

In [8]:
from sklearn.linear_model import LogisticRegression
X = [[1],[2],[3],[4],[5]]
Y = [0,0,1,1,1]

model = LogisticRegression()
model.fit(X,Y)

hrs = float(input('enter your study hrs: '))
result = model.predict([[hrs]])[0]

if result == 1:
     print(f"based on your study hours {hrs}, you are likey to PASS..!")
else:
     print(f"based on your study hours {hrs}, you are likey to FAIL.!")

based on your study hours 4.0, you are likey to PASS..!

- KNN Classification

In [15]:
# 0:Apple & 1:Orange
from sklearn.neighbors import KNeighborsClassifier
X = [
     [180,7],
     [200,7.5],
     [250,8],
     [300,8.5],
     [330,9],
     [360,9.5]
]
Y = [0,0,0,1,1,1]
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X,Y)

wt = float(input('enter weight in grams: '))
size = float(input('enter thesize in cm: '))

prediction = model.predict([[wt,size]])[0]

if prediction == 0:
     print("Likely an Apple..!")
else:
     print("Likely an Orange..!")

Likely an Apple..!

- Decision Tree

In [16]:
from sklearn.tree import DecisionTreeClassifier

X = [
     [7,2],
     [8,3],
     [9,8],
     [10,9]
]
Y = [0,0,1,1]
# Apple:0 & Orange:1

model = DecisionTreeClassifier()
model.fit(X,Y)

size = float(input('enter fruit size in cm: '))
shade = float(input('enter color shade(1-10): '))

res = model.predict([[size,shade]])[0] # [0] return only answer not packed result

if res == 0:
     print("Likely an Apple..!")
else:
     print("Likely an Orange..!")

Likely an Orange..!

- accuracy = correct_pred / total_pred

In [1]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

# actual answers
y_true = [1,0,1,1,0,1,0]

# model prediciton (gussed)
y_pred = [1,0,1,0,0,1,1]

## evaluation
print(f"Accuracy:{accuracy_score(y_true,y_pred)}")
print(f"Precision:{precision_score(y_true,y_pred)}")
print(f"Recall:{recall_score(y_true,y_pred)}")
print(f"F1 Score:{f1_score(y_true,y_pred)}")

Accuracy:0.7142857142857143
Precision:0.75
Recall:0.75
F1 Score:0.75

In [2]:
from sklearn.metrics import confusion_matrix
## Confusion Matrix
y_true = [1,0,1,1,0,1,0,0,1,0]
y_pred = [1,0,1,0,0,1,1,0,1,0]

cm = confusion_matrix(y_true,y_pred)
print("Confusion Matrix")
print(cm)

Confusion Matrix
[[4 1]
 [1 4]]

In [3]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
import numpy as np

## real score
real_scores = [90,78,99,100]

## model guessed
predicted_score = [89,70,90,97]

mae = mean_absolute_error(real_scores,predicted_score)
mse = mean_squared_error(real_scores,predicted_score)

rmse = np.sqrt(mse)

print(f"MAE:On Average off by: {mae}")
print(f"MSE:Squared Nistake Value: {mse}")
print(f"RMSE:Final Realistic Error: {rmse}")

MAE:On Average off by: 5.25
MSE:Squared Nistake Value: 38.75
RMSE:Final Realistic Error: 6.224949798994366

- Project Revision

In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.DataFrame({
     "Hours":[1,2,3,4,5,6,7,8],
     "Score":[34,45,78,89,90,88,90,99]
})
df

   Hours  Score
0      1     34
1      2     45
2      3     78
3      4     89
4      5     90
5      6     88
6      7     90
7      8     99

In [5]:
df.head()

   Hours  Score
0      1     34
1      2     45
2      3     78
3      4     89
4      5     90

In [6]:
X = df.drop(["Score"],axis=1)
Y = df['Score']

In [7]:
X.head()

   Hours
0      1
1      2
2      3
3      4
4      5

In [8]:
Y.head()

0    34
1    45
2    78
3    89
4    90
Name: Score, dtype: int64

In [10]:
model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [11]:
y_pred = model.predict(X)

In [12]:
y_pred

array([ 47.        ,  55.46428571,  63.92857143,  72.39285714,
        80.85714286,  89.32142857,  97.78571429, 106.25      ])

In [13]:
## evaluation metrics
mae = mean_absolute_error(Y,y_pred)
mse = mean_squared_error(Y,y_pred)
rmse = np.sqrt(mse)

print("MAE:",mae)
print("MSE:",mse)
print("RMSE:",rmse)

MAE: 9.955357142857142
MSE: 118.85267857142853
RMSE: 10.901957556853198