### Pandas Fundamentals Day_10
***
#### Pandas 
- This librarey used for data analysis and data manipulation.
- Built on top of Numpy.
- Easier work with tabular,labeled or hetrogeneous datasets.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
     "Name":["Alex","Alice"],
     "Cgpa":[9.7,9.1]
})
print(df)
print(type(type))

    Name  Cgpa
0   Alex   9.7
1  Alice   9.1
<class 'type'>

### Series In Pandas 
- 1D Labeled Array
- It can hold data of any type like as integers, floats, strings, Python objects.
- components
   - index  (label for each value)
   - values (actual data)

In [2]:
s = pd.Series([23,34,45,78,88])
print(s)
print(type(s))

## indexing 
print(s[0])
print(s[2])
print(s.index)

0    23
1    34
2    45
3    78
4    88
dtype: int64
<class 'pandas.core.series.Series'>
23
45
RangeIndex(start=0, stop=5, step=1)

In [3]:
## custom indexing
series = pd.Series([23,44,57,89],index=["A","B","C","D"])
print(series["A"])
print(series["C"])

23
57

In [4]:
## Vectorized operation
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([7,8,9,10])
print(s1+s2)

0     8
1    10
2    12
3    14
dtype: int64

In [5]:
## Mutable Values but immutable size
s = pd.Series([1,2,3,4,57,8,9])
s[2] = 120
print(s)

changed_series = s.drop(1)
print(changed_series)

0      1
1      2
2    120
3      4
4     57
5      8
6      9
dtype: int64
0      1
2    120
3      4
4     57
5      8
6      9
dtype: int64

- **DataFrame**
   - 2D,tabular datastructure
   - It consits rows | columns | index | column labels.

In [ ]:
## Datafram in pandas  using (Dictionary)
info = {
    "Name" : ["Adam", "Eve", "Bob"],
    "Marks" : [78, 99, 85],
    "Grade" : ['B', 'O', 'A']
}

df = pd.DataFrame(info)
df

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A

In [7]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
print(df.index)  # row labels
print(df.columns) # columns label

RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Grade'], dtype='object')

In [9]:
## Dataframe in pandas  using (Numpy Array)
arr = np.array([[1,2,3],[4,5,7],[8,9,10]])
df = pd.DataFrame(arr,columns=['A','B','C'])
df

   A  B   C
0  1  2   3
1  4  5   7
2  8  9  10

In [10]:
## Dataframe in pandas  using (Lists)
lst = [["Ankit",99],["Kush",97],["Kavi",90],["Ankit",95]]
df = pd.DataFrame(lst,columns=["Name","Marks"])
df

    Name  Marks
0  Ankit     99
1   Kush     97
2   Kavi     90
3  Ankit     95

#### Extracting Data From CSV File | JOSN File

In [11]:
## Pandas with csv file
data = pd.read_csv("employee_data.csv")
data

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [12]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [13]:
## Pandas as JSON File
json_data = pd.read_json("employ.json")
json_data

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [14]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [15]:
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

#### Dataframe Methods

In [16]:
print(df.head())

   id          name   age country   gender   income
0   1      John Doe  29.0     USA     Male  55000.0
1   1      John Doe  29.0     USA     Male  55000.0
2   2    Jane Smith   NaN  Canada   Female  62000.0
3   3          Alex   NaN     USA  Unknown  47000.0
4   4  Maria Garcia  34.0   Spain   Female      NaN

In [17]:
print(df.tail())

    id         name   age country  gender   income
6    6          NaN  45.0   India  Female  73000.0
7    7   Ahmed Khan  38.0     NaN    Male  68000.0
8    8   Rachel Lee  29.0     USA  Female  62000.0
9    9  Carlos Ruiz   NaN  Mexico    Male  45000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

In [18]:
print(df.sample())

   id        name   age country gender   income
7   7  Ahmed Khan  38.0     NaN   Male  68000.0

In [19]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes
None

In [20]:
print(df.shape)

(11, 6)

In [21]:
print(df.describe())

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [22]:
print(df.columns)

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='object')

In [23]:
print(df.nunique())

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64

In [28]:
df = pd.read_csv("Amazon.csv")
df

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD0099996,2023-03-07,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,0.00,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041
99996,ORD0099997,2021-11-24,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,0.00,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449
99997,ORD0099998,2023-04-29,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,0.00,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028
99998,ORD0099999,2021-11-01,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,0.00,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324
99999,ORD0100000,2021-12-04,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,0.05,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761

In [29]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [30]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

In [31]:
df.describe()

,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,3.001400,302.905748,0.074226,68.468902,7.406660,918.256479
std,1.413548,171.840797,0.082583,74.131180,4.324057,724.508332
min,1.000000,5.000000,0.000000,0.000000,0.000000,4.270000
25%,2.000000,154.190000,0.000000,15.920000,3.680000,340.890000
50%,3.000000,303.070000,0.050000,45.250000,7.300000,714.315000
75%,4.000000,451.500000,0.100000,96.060000,11.150000,1349.765000
max,5.000000,599.990000,0.300000,538.460000,15.000000,3534.980000

In [32]:
df.tail()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
99995,ORD0099996,2023-03-07,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,0.00,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041
99996,ORD0099997,2021-11-24,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,0.00,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449
99997,ORD0099998,2023-04-29,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,0.00,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028
99998,ORD0099999,2021-11-01,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,0.00,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324
99999,ORD0100000,2021-12-04,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,0.05,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761

In [36]:
## Selecting Data
df["City"]

0          Washington
1          Fort Worth
2              Austin
3           Charlotte
4         San Antonio
             ...
99995    Jacksonville
99996        San Jose
99997    Indianapolis
99998       Charlotte
99999        New York
Name: City, Length: 100000, dtype: object

- By index label (loc) - Use row labels (if you have custom index) or column names.
-  In loc when we slice, the ending index is inclusive.

In [38]:
## Select Rows (by label)
df.loc[0]

OrderID             ORD0000001
OrderDate           2023-01-31
CustomerID          CUST001504
CustomerName     Vihaan Sharma
ProductID               P00014
ProductName         Drone Mini
Category                 Books
Brand                BrightLux
Quantity                     3
UnitPrice               106.59
Discount                   0.0
Tax                        0.0
ShippingCost              0.09
TotalAmount             319.86
PaymentMethod       Debit Card
OrderStatus          Delivered
City                Washington
State                       DC
Country                  India
SellerID             SELL01967
Name: 0, dtype: object

In [ ]:
df.loc[:3] # inclusive last index in loc

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164

- By index position (iloc) - Use integer positions.
- In iloc when we slice, the ending index is exclusive.

In [42]:
## select rows (by index)
df.iloc[0]

OrderID             ORD0000001
OrderDate           2023-01-31
CustomerID          CUST001504
CustomerName     Vihaan Sharma
ProductID               P00014
ProductName         Drone Mini
Category                 Books
Brand                BrightLux
Quantity                     3
UnitPrice               106.59
Discount                   0.0
Tax                        0.0
ShippingCost              0.09
TotalAmount             319.86
PaymentMethod       Debit Card
OrderStatus          Delivered
City                Washington
State                       DC
Country                  India
SellerID             SELL01967
Name: 0, dtype: object

In [43]:
df.iloc[3:7]

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411
5,ORD0000006,2022-12-31,CUST042705,Karan Sharma,P00023,Cookware Set,Books,ReadMore,4,449.73,0.00,215.87,2.74,2017.53,UPI,Delivered,Los Angeles,CA,United States,SELL01494
6,ORD0000007,2024-09-20,CUST037667,Aarav Verma,P00030,Dress Shirt,Clothing,UrbanStyle,2,219.81,0.20,28.14,14.97,394.81,UPI,Delivered,Chicago,IL,Australia,SELL01676

In [46]:
## Select Rows & Columns
df.loc[4,"Country"]

'Canada'

In [50]:
df.iloc[2,3]

'Sneha Singh'

In [51]:
df.iloc[0,1:7]

OrderDate          2023-01-31
CustomerID         CUST001504
CustomerName    Vihaan Sharma
ProductID              P00014
ProductName        Drone Mini
Category                Books
Name: 0, dtype: object

In [52]:
df.loc[2,["Country","City"]]

Country    United States
City              Austin
Name: 2, dtype: object

In [53]:
df.loc[0:5,["Country","City","Tax"]] # end is inclusive

         Country         City     Tax
0          India   Washington    0.00
1  United States   Fort Worth   19.10
2  United States       Austin    7.57
3          India    Charlotte   11.42
4         Canada  San Antonio   38.67
5  United States  Los Angeles  215.87

In [54]:
df.iloc[0:5, 1:3]

    OrderDate  CustomerID
0  2023-01-31  CUST001504
1  2023-12-30  CUST000178
2  2022-05-10  CUST047516
3  2023-07-18  CUST030059
4  2023-02-04  CUST048677

In [59]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

- We have at & iat for fast access to single cells.

In [57]:
# Select single scalar value
df.at[0, "City"]

'Washington'

In [60]:
df.iat[0, 2]

'CUST001504'

In [ ]:
## Filtering & Querying Data.
df[df["UnitPrice"] > 100]

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411
5,ORD0000006,2022-12-31,CUST042705,Karan Sharma,P00023,Cookware Set,Books,ReadMore,4,449.73,0.00,215.87,2.74,2017.53,UPI,Delivered,Los Angeles,CA,United States,SELL01494
6,ORD0000007,2024-09-20,CUST037667,Aarav Verma,P00030,Dress Shirt,Clothing,UrbanStyle,2,219.81,0.20,28.14,14.97,394.81,UPI,Delivered,Chicago,IL,Australia,SELL01676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD0099996,2023-03-07,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,0.00,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041
99996,ORD0099997,2021-11-24,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,0.00,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449
99997,ORD0099998,2023-04-29,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,0.00,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028
99998,ORD0099999,2021-11-01,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,0.00,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324
99999,ORD0100000,2021-12-04,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,0.05,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761

In [62]:
df[df["UnitPrice"] > 100][["Brand","Country"]]

            Brand        Country
0       BrightLux          India
1      UrbanStyle  United States
4        KiddoFun         Canada
5        ReadMore  United States
6      UrbanStyle      Australia
...           ...            ...
99995        Apex          India
99996        Apex  United States
99997   BrightLux  United States
99998    HomeEase  United States
99999    CoreTech  United States

[84106 rows x 2 columns]

In [63]:
data = df[(df["UnitPrice"] > 100) & (df["Brand"] == "UrbanStyle")][["Brand", "Country"]]

In [64]:
data

            Brand         Country
1      UrbanStyle   United States
6      UrbanStyle       Australia
26     UrbanStyle   United States
51     UrbanStyle   United States
57     UrbanStyle          Canada
...           ...             ...
99918  UrbanStyle   United States
99921  UrbanStyle  United Kingdom
99966  UrbanStyle          Canada
99987  UrbanStyle   United States
99989  UrbanStyle   United States

[8301 rows x 2 columns]

In [68]:
## Query: Returns Copy Not View
data = df[(df["UnitPrice"] > 100) & (df["Brand"] == "Zenith")][["Brand", "Country"]]
data

        Brand        Country
12     Zenith  United States
16     Zenith  United States
28     Zenith  United States
40     Zenith  United States
64     Zenith          India
...       ...            ...
99972  Zenith  United States
99974  Zenith  United States
99982  Zenith  United States
99988  Zenith  United States
99992  Zenith  United States

[8395 rows x 2 columns]

### Pandas Fundamentals Day_11
***

In [8]:
## Cleaning Data
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

- Query Method
  - df.query()

In [19]:
result = df.query("income < 50000 and country == 'India'", engine="python")
result

Empty DataFrame
Columns: [id, name, age, country, gender, income]
Index: []

#### Handle Missing Value

In [ ]:
df.isnull() # True for missing values

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [71]:
df.isnull().sum() # counts missing values

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [72]:
df.dropna() # drops rows with missing values

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [73]:
df.dropna(axis = 1)  
# drops cols with missing values.

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [74]:
df.fillna(0)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [77]:
df["age"] = df["age"].fillna(df["age"].mean())

In [78]:
df

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [79]:
df.ffill()  # forward fill

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  47000.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6        Li Wei  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00   India     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA     Male  58000.0

In [80]:
df.bfill()  # backward fill

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  51000.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6    Ahmed Khan  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     USA     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

#### Handle Duplicates value

In [81]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [82]:
df.duplicated("country")

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
dtype: bool

In [83]:
df.duplicated(["country", "gender"])

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [84]:
df.drop_duplicates()

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

#### Handle Data Types

In [85]:
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [22]:
df1 = df.fillna(0).copy()
df1['income'] = df1['income'].astype(int) # change dtype

In [23]:
## String Type
df1["gender"].str.lower()

0        male
1        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: object

In [25]:
df2 = df1.copy()
df2["income"] = df2["income"].astype(int)   # change dtype  

date_str = "2025-12-01"  
date = pd.to_datetime(date_str)  
print(date)  
print(type(date))

2025-12-01 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [88]:
df1["gender"].str.upper()

0        MALE
1        MALE
2      FEMALE
3     UNKNOWN
4      FEMALE
5        MALE
6      FEMALE
7        MALE
8      FEMALE
9        MALE
10        NaN
Name: gender, dtype: object

In [89]:
df1["gender"].str.capitalize()

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object

In [ ]:
df1["name"].str.split(" ")
# splits into lists based on separator value

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [92]:
type(df1["name"].str.split(" ")[0])

list

In [93]:
df1["country"].str.contains("US")
df1["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object